version: '3.7'

services:
  proxy:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./images:/home/images
    restart: always
    networks:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - frontend

  backend:
    build:
      context: ./backend
      target: production-build-stage
      dockerfile: Dockerfile
    volumes:
      - ./images:/images
    restart: always
    depends_on:
      - postgres
    networks:
      - backend

networks:
  frontend:
  backend:
